global:
  envName: "staging"
backend:
  replicaCount: 3 # Scaled for localized testing simulations
  image:
    repository: "mithunkumarb2026/supermarket-backend"
    tag: "ef63a5602c657b486fe5231d9cfb9ce66ad6d5a1"
frontend:
  replicaCount: 2
  image:
    repository: "mithunkumarb2026/supermarket-frontend"
    tag: "ef63a5602c657b486fe5231d9cfb9ce66ad6d5a1"
otel:
  collectorEndpoint: "http://otel-collector-infrastructure-opentelemetry-collector.monitoring.svc.cluster.local:4317"