global:
  envName: "dev"
backend:
  replicaCount: 1
  image:
    repository: "mithunkumarb2026/supermarket-backend"
    tag: "ef63a5602c657b486fe5231d9cfb9ce66ad6d5a1" # Overwritten automatically by your GitHub Actions SHA
frontend:
  replicaCount: 1
  image:
    repository: "mithunkumarb2026/supermarket-frontend"
    tag: "ef63a5602c657b486fe5231d9cfb9ce66ad6d5a1" # Overwritten automatically by your GitHub Actions SHA
otel:
  collectorEndpoint: "http://otel-collector-infrastructure-opentelemetry-collector.monitoring.svc.cluster.local:4317"