apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: loki
    targetRevision: 5.47.2
    helm:
      values: |
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          persistence:
            enabled: false

          structuredConfig:
            common:
              instance_addr: 127.0.0.1
              path_prefix: /var/loki
              replication_factor: 1
              storage:
                filesystem:
                  chunks_directory: /var/loki/chunks
                  rules_directory: /var/loki/rules
            limits_config:
              reject_old_samples: true
              reject_old_samples_max_age: 168h
            server:
              http_listen_port: 3100
            ingester:
              lifecycler:
                address: 127.0.0.1
                ring:
                  kvstore:
                    store: inmemory
                  replication_factor: 1

        singleBinary:
          replicas: 1
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0

        test:
          enabled: false

        monitoring:
          dashboards:
            enabled: false
          rules:
            enabled: false
          alerts:
            enabled: false
          serviceMonitor:
            enabled: false
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          lokiCanary:
            enabled: false

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true