apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supermarket-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/BMithunKumar/supermarket-app-lgtm-argocd-infra.git'
    targetRevision: HEAD
    path: helm/super-market-app
    helm:
      valueFiles:
        - values.staging.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: market-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true