apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: loki
    targetRevision: 5.47.2 
    helm:
      values: |
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          persistence:
            enabled: false
          
        singleBinary:
          replicas: 1
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0

        test:
          enabled: false

        # TURN OFF ALL EXTERNAL PROMETHEUS/GRAFANA OPERATOR RULES:
        monitoring:
          dashboards:
            enabled: false
          rules:
            enabled: false
          alerts:
            enabled: false
          serviceMonitor:
            enabled: false
          selfMonitoring:
            enabled: false
          # This prevents it from looking for grafanaagents.monitoring.grafana.com
          lokiCanary:
            enabled: false