apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 61.3.0
    helm:
      values: |
        grafana:
          enabled: true
          adminPassword: "admin"
          additionalDataSources:
            - name: Loki
              type: loki
              access: proxy
              url: http://lgtm-stack-loki-gateway.monitoring.svc.cluster.local:3100
            - name: Tempo
              type: tempo
              access: proxy
              url: http://lgtm-stack-tempo-distributor.monitoring.svc.cluster.local:4317

        loki-distributed:
          enabled: true
          loki:
            structuredConfig:
              auth_enabled: false

        tempo-distributed:
          enabled: true

        mimir-distributed:
          enabled: true
          mimir:
            structuredConfig:
              multitenancy_enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # ADD THESE CRITICAL SYNC OPTIONS TO FIX THE TOO LONG BYTES ERROR:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Forces K8s to handle the massive CRDs on the server side instead of using annotations
      - SkipDryRunOnMissingResource=true # Prevents Argo from panicking while the CRDs are spinning up