apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 25.27.0
    helm:
      values: |
        alertmanager:
          enabled: false
        prometheus-pushgateway:
          enabled: false
        server:
          persistentVolume:
            enabled: false
          extraArgs:
            web.enable-remote-write-receiver: ""
            web.enable-lifecycle: ""
          extraScrapeConfigs: |
            - job_name: 'otel-collector'
              scrape_interval: 5s
              static_configs:
                - targets: ['otel-collector-infrastructure-opentelemetry-collector.monitoring.svc.cluster.local:8889']
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true